### PR TITLE
added "visibility: hidden" for tnsl-random

### PR DESCRIPTION
**Pull request by kouul**

### CODE REVIEW

**Comment by Antrikshy** [comment]
Hi, thanks for the PR!

The \*.min.* files are not supposed to be touched by hand. I initially meant to comment on this PR saying you should make your changes in the src directory and get Gulp to handle generating the min files, but as I tried to replicate this, I noticed the build tools were not working correctly probably because they are out of date. I just updated everything using a modern npm version and bumped major versions of the dev dependencies to make the package actually functional in 2019.

So, please go make any changes in the src directory. However, before you do that, can you briefly explain what your change intends to do?

**Comment by kouul** [comment]
Hello there,
I noticed, when using tnsl-random on a particular div, that the div will be visible even before the effect takes place, which is not the case when using the other classes(tnsl-flicker..). From what I understand, the page should load first, then the effects would take place, is that correct?
So I set the visibility of any element with the class 'tnsl-random' to hidden, similar to that of 'tnsl-slideFromLeft'. In this way, the page would load first, then a random effect will take place on that div.

Should i proceed to make the change or is this the correct behaviour?

**Comment by Antrikshy** [comment]
Ahh I didn’t realize this was the case. Yep, sounds good! I’ve added documentation at the bottom of the README that explains how to actually test changes better. I hope it’s helpful!

**Comment by kouul** [comment]
I was having some issues running the npm install locally. I had to delete the repo on my side and forked it again. I've created another pull request for the matter, so I guess you can close this one.

**Pull request closed without merging**
